### PR TITLE
feat: support config overwrite via URL parameters

### PR DESCRIPTION
**Pull request by csett86**
Signed-off-by: Christoph Settgast <csett86@web.de>

### CODE REVIEW

**Comment by csett86** [comment]
I tested this successfully with the examples from #67 like config.disableAP=true&config.disableAEC=true&config.disableNS=true&config.disableAGC=true&config.disableHPF=true&config.stereo=true

I chose to put it after the app settings so that one can individually override for a conference the settings done in general in the app.

**Comment by csett86** [comment]
Currently not supported is the nested ones like config.p2p.*

**Review by saghul — APPROVED** [review]

**Comment by rogeriomq** [comment]
In the jitsi-meet project, there is a function that does this parse and returns a complete object that comes via hashParams([src/react/features/base/util/parseURLParams.js](https://github.com/jitsi/jitsi-meet/blob/da7358d5648175c546878e6ec3889d68e93ed8b9/react/features/base/util/parseURLParams.js)).
I made use of parseURLParams, and besides props for configOverwrite, I also retrieve other custom keys and also userInfo.

I will try to replicate and perform a pullRequest.
But the idea is already there.  😊

**Comment by bilogic** [comment]
Is there a way to tell if AP has been disabled in the electron app? Or must we rely on our ears?

**Comment by saghul** [comment]
You could open the dev console (same shortcut as in a Chrome browser) and check.

**Pull request merged**
