### PR TITLE
hu locale

### PR DESCRIPTION
**Pull request by ovari**

### CODE REVIEW

**Comment by ovari** [comment]
@saghul can you please help as all checks have failed and we would like to merge this with your code? Thank you

**Comment by saghul** [comment]
You can run npm run lint and you'll see. Line 17 has some bad formatted JSON it seems.

**Comment by ovari** [comment]
Thanks for the pointer to line 17. We don't have npm as this is done only using GitHub's web editor.

**Comment by ovari** [comment]
@saghul can you please merge this as all checks have passed? Thank you

**Comment by saghul** [comment]
Cheers!

**Comment by ovari** [comment]
Thanks @saghul for merging.

Can you please advise when the release with the Hungarian translation will be available at https://github.com/jitsi/jitsi-meet-electron/#installation?

Thank you once again.

**Comment by saghul** [comment]
Now sure when we'll make a new build.

**Pull request merged**
