### PR TITLE
2023.11.2

### PR DESCRIPTION
**Pull request by gabiborlea**

### CODE REVIEW

**Review by saghul — APPROVED** [review]

**Comment by p-schneider** [comment]
v2023.11.2 is tagged at f8ee5c7b94b87a562c00f67b671720af06e4c9da but the master branch is at commit 22adc4b5890ff966e5136c09fb45cfca2d5817a5 (2 different commits, but with the same commit message).
Is that on purpose or by accident?

**Comment by gabiborlea** [comment]
I created the release from the PR branch, maybe that's why, not on purpose, just my first releases here :)

**Comment by csett86** [comment]
The README of this project has a section on how to release (within the development instructions)

**Comment by gabiborlea** [comment]
Eventually followed them, thank you!

**Comment by csett86** [comment]
Sorry that its a bit of a manual and not so intuitive way to release at the moment, I never got around to wrap parts of it into some github action so that it would be easier and more intuitive...

**Comment by saghul** [comment]
No worries at all, thanks for all the automation work you've already done!

**Pull request merged**
