### PR TITLE
BREAKING CHANGE: Switch to local storage

### PR DESCRIPTION
**Pull request by csett86**
electron-storage with its current version is unsupported on Electron 14+ (due to
remote module removal), electron-storage 7+ is really slow (10 seconds on start),
thus switch to local storage.

Unfortunately all settings are lost, as migrating from electron-storage
to local storage is not feasible without continuing to have slow initial
startup times.

### CODE REVIEW

**Comment by saghul** [comment]
Is there no electron-storage version that works? Wow.

**Review by saghul — APPROVED** [review]

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Let's bump the major then, since people will lose their display name.

**Comment by csett86** [comment]
I found a way to migrate the settings (and thus avoid the breakage), then we can at least ship a version with electron 13 and migrate to local storage and only later on remove electron-store when updating to electron 14.

I suggest a 3 months migration period before removing electron-store and the migration.

See #638 for all the details, closing this breaking change in favor of it.

**Comment by saghul** [comment]
Excellent!

**Pull request closed without merging**
