### PR TITLE
Added start with Audio and Video Muted Toggles

### LINKED ISSUE #53: settings: add ability to start with audio / video muted

### PR DESCRIPTION
**Pull request by akshitkrnagpal**
Resolves #53.

### CODE REVIEW

**Comment by akshitkrnagpal** [comment]
> What makes me a bit uneasy is that !important you added for the colour of the label. We shouldn't do that since this won't work, should we ever decide to change themes.

That actually makes the color of the labels same as the color of labels for input fields.

> I'm not sure I like the layout.

Green toggles also look weird to me actually. 
@saghul 
How about we feel about doing this with icons?
screenshot from 2018-07-02 12-12-32 screenshot from 2018-07-02 12-13-28 screenshot from 2018-07-02 12-14-03

**Comment by saghul** [comment]
Yeah, I guessed you were trying to color match them, but if the AtlaskitTheme changes our color doesn’t.

The green toggles look fine to me TBH!

About putting the controls on the welcome page: I’m not sure I’ll like them, but let’s experiment! Maybe they feel better indeed!

Feel free to also play with other controls such as checkboxes or the icons themselves in the drawer too and let’s see what looks and feels best.

**Comment by akshitkrnagpal** [comment]
> I'm assuming a toggle would look the same.

Yeah. I have updated this to that.

> About putting the controls on the welcome page: I’m not sure I’ll like them, but let’s experiment! Maybe they feel better indeed!

Yeah. I tried a bunch of stuff. Couldn't make it look good. :upside_down_face: 


screenshot from 2018-07-02 20-44-16

In drawer, toggles look best.

Ping @saghul.

**Comment by saghul** [comment]
@akshitkrnagpal I love that screenshot! Let's keep it like that please!

**Comment by akshitkrnagpal** [comment]
> @akshitkrnagpal I love that screenshot! Let's keep it like that please!

Cool.

**Comment by saghul** [comment]
🎉 🎉 🎉

**Pull request merged**
