### PR TITLE
feat(wayland): enable titlebar when running under wayland

### PR DESCRIPTION
**Pull request by csett86**
Use with --ozone-platform-hint=auto to enable

Closes: #683

### CODE REVIEW

**Comment by csett86** [comment]
This does not look right under Wayland (Ubuntu 22.04), so please don't merge for now. Will convert to a draft as well.

grafik

**Comment by csett86** [comment]
I have reported the wayland titlebar issue upstream as https://github.com/electron/electron/issues/34820

**Comment by csett86** [comment]
Now looking good after the electron update that contains the fixes:

image

**Comment by csett86** [comment]
@saghul please review, I tested it successfully on Windows 10, macOS 12.5 and Ubuntu 22.04

**Comment by csett86** [comment]
After this I would cut the August release: #783

**Review by saghul — APPROVED** [review]

**Pull request merged**
