### PR TITLE
Update jitsi-meet-electron-utils to be ready for electron 14+

### PR DESCRIPTION
**Pull request by csett86**

### CODE REVIEW

**Comment by csett86** [comment]
Tested successfully, I will change to a commit on master of jitsi-meet-electron-utils once https://github.com/jitsi/jitsi-meet-electron-utils/pull/134 is merged.

**Review by saghul — APPROVED** [review]

**Review by saghul — CHANGES_REQUESTED** [review]
Let's guard it with a constant check, we don't want this to eventually be enabled by mistake.

**Comment by csett86** [comment]
Agree, will add a guard similar to the Conference.js guard for remotecontrol

**Comment by csett86** [comment]
Now properly guarded for main process as well

**Review by saghul — APPROVED** [review]

**Comment by csett86** [comment]
I will dig deeper why the windows builds are now both failing with npm8 / node 16, both here and https://github.com/jitsi/jitsi-meet-electron-utils/pull/135 with the same error.

Until then not going to merge this, as otherwise we no longer have a windows build...

**Comment by csett86** [comment]
The windows build is now fixed here as well.

**Review by saghul — APPROVED** [review]

**Pull request merged**
