### PR TITLE
2021.12.1

### PR DESCRIPTION
**Pull request by csett86**
- 2021.12.0
- 2021.12.1

### CODE REVIEW

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
I'm getting this error when updating, does it sound familiar?

```
12:49:52.615 › updater cache dir: /Users/saghul/Library/Application Support/Caches/jitsi-meet-electron-updater
12:49:53.199 › Update has already been downloaded to /Users/saghul/Library/Application Support/Caches/jitsi-meet-electron-updater/pending/jitsi-meet.zip).
12:49:53.200 › Creating proxy server for native Squirrel.Mac (fileToProxy=https://github.com/jitsi/jitsi-meet-electron/releases/download/v2021.12.1/jitsi-meet.zip)
12:49:53.201 › Error: TypeError: Cannot read property 'port' of null
    at p (/Applications/Jitsi Meet.app/Contents/Resources/app-x64.asar/build/main.js:1:94888)
    at l.updateDownloaded (/Applications/Jitsi Meet.app/Contents/Resources/app-x64.asar/build/main.js:1:95058)
    at Object.done (/Applications/Jitsi Meet.app/Contents/Resources/app-x64.asar/build/main.js:1:94556)
    at f (/Applications/Jitsi Meet.app/Contents/Resources/app-x64.asar/build/main.js:1:47403)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async l.executeDownload (/Applications/Jitsi Meet.app/Contents/Resources/app-x64.asar/build/main.js:1:47531)
(node:81716) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of null
    at p (/Applications/Jitsi Meet.app/Contents/Resources/app-x64.asar/build/main.js:1:94888)
    at l.updateDownloaded (/Applications/Jitsi Meet.app/Contents/Resources/app-x64.asar/build/main.js:1:95058)
    at Object.done (/Applications/Jitsi Meet.app/Contents/Resources/app-x64.asar/build/main.js:1:94556)
    at f (/Applications/Jitsi Meet.app/Contents/Resources/app-x64.asar/build/main.js:1:47403)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async l.executeDownload (/Applications/Jitsi Meet.app/Contents/Resources/app-x64.asar/build/main.js:1:47531)
(Use `Jitsi Meet --trace-warnings ...` to show where the warning was created)
(node:81716) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:81716) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by saghul** [comment]
Looks like we need to update electron-updater: https://github.com/electron-userland/electron-builder/issues/6170 patching incoming.

**Comment by csett86** [comment]
This was an issue in 2.9.1 - 2021.11.1, but should already be fixed with 2021.11.2: https://github.com/jitsi/jitsi-meet-electron/commit/935515d7ce71c76730280dd38b8cbd864a85bdd3

**Comment by saghul** [comment]
Gotcha. Updated the dependency none the less. No rush to merge then.

**Comment by saghul** [comment]
Verified updating from the november release. Works fine!

**Pull request merged**
