### PR TITLE
Adding sq translation

### PR DESCRIPTION
**Pull request by ujdhesa**
Here you are a translation for sq locale. 

TIA

### CODE REVIEW

**Comment by saghul** [comment]
You need to add it here too: https://github.com/jitsi/jitsi-meet-electron/blob/master/app/i18n/index.js

**Comment by saghul** [comment]
There is a syntax error check the trailing commas

**Comment by ujdhesa** [comment]
> There is a syntax error check the trailing commas
I hope that was the right to blame.

**Comment by saghul** [comment]
Now you're missing the comma after the nl locale. Please test your code.

**Comment by ujdhesa** [comment]
> Now you're missing the comma after the nl locale. Please test your code.
I apologise for having overlooked again.

**Review by saghul — APPROVED** [review]

**Pull request merged**
