### PR TITLE
Fix recent list  to skip tokens

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by saghul** [comment]
@csett86 PTAL. I made it so all entried will be normalized after a meeting is updated.

**Review by csett86 — APPROVED** [review]
Looks good to me, a quick test also worked well, thank you @saghul

**Comment by damencho** [comment]
We got a question about this in the community call, is it possible to keep the config options and just drop the jwt?

**Comment by saghul** [comment]
It should be possible, yeah.

**Pull request merged**
