### PR TITLE
Flatpak from Flathub link

### PR DESCRIPTION
**Pull request by ovari**

### CODE REVIEW

**Comment by saghul** [comment]
I don't know who publishes that so I'm not very comfortable recommending users to install it.

**Comment by ovari** [comment]
@ananace can you please make yourself known to @saghul so that https://github.com/flathub/org.jitsi.jitsi-meet/ can be added to [README.md](https://github.com/jitsi/jitsi-meet-electron/blob/master/README.md)?

**Comment by ananace** [comment]
Personally, I'd not call it a "Flathub download" as Flathub is just a repository and not the download, just the word "Flathub", "Flatpak", or something like "Available on Flathub" would be a much better way to describe it.
Perhaps marking it as third-party would be for the best too, to make it even more clear that any Flatpak-specific issues should be directed to there. (Unless the Jitsi team wishes to also take maintainership of the Flatpak, which they're more than welcome to)

On a side note, the Flatpak is done to require - and cause - as little work for here as possible; it's basically just taking the regular AppImage, unpacking it into the sandbox, fixing the desktop exec and icon, and adding some metainfo/appdata XML as required by Flathub.

**Comment by ovari** [comment]
> Personally, I'd not call it a "Flathub download" as Flathub is just a repository and not the download, just the word "Flathub", "Flatpak", or something like "Available on Flathub" would be a much better way to describe it.

Thanks, fixed.

> I'm not very comfortable recommending users to install it.

@saghul would @ananace giving you full access to https://github.com/flathub/org.jitsi.jitsi-meet/ help?

**Comment by ananace** [comment]
And as a note on that; I'm not the person to give out that access, that would have to be from the Flathub people - who are more than happy to transfer ownership to the upstream teams that wish to handle their own packages.

**Comment by ovari** [comment]
Can you please add the Flathub people to this issue? Thank you

**Comment by ananace** [comment]
I'd quite like to wait for the Jitsi team to decide that they wish to take ownership of the Flathub packaging before dragging them into that.

The reason I did the Flathub addition in the first place was because there had been requests (#320, #426) for a Flatpak package before, which were closed due to lack of time to spend on it. I'd not wish to force them to add that extra bit of burden if that's still true.

**Comment by ovari** [comment]
https://github.com/flathub/org.jitsi.jitsi-meet/issues/4#issuecomment-699558884

@saghul can you please accept the patch?

**Comment by saghul** [comment]
What patch? Just to be clear, while I'm happy to take a patch that would make this easier for you, we have no resources to devote to this, so while we can add it to the README it will be with a "Third-Party builds" heading or something similar.

**Comment by ovari** [comment]
Sorry, there was a patch but then we added the flathub/flatpak attempt to translate the Desktop file which GitHub advised didn't work. We are doing this all in the web-based interface. It didn't work so we deleted it.

**Pull request closed without merging**
