### PR TITLE
chore(deps) update Electron to 24

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by saghul** [comment]
@csett86 WDYT about landing this and making a new release? We haven't done one in a bit...

**Comment by csett86** [comment]
I'll take a look tomorrow. I was holding back the electron upgrade as it will break screensharing on wayland (segfault on trying), but as it does not seem to get fixed, I will add a bigger warning in the readme as a known issue together with this PR

**Comment by saghul** [comment]
Thanks! Yeah that's unfortunate but 21 is EOLd so I think we have to upgrade.

**Review by csett86 — APPROVED** [review]
Looks good, tested successfully under mac OS 13, Windows 10. Linux works fine as well, apart from screensharing under wayland, which still segfaults. I will reopen #829 accordingly

**Pull request merged**
