### PR TITLE
chore: Upgrade CI Dependencies to Latest Version

### PR DESCRIPTION
**Pull request by RudraSen2**
Upgrading CI Dependencies to Latest Version. Tested and Verified.

### CODE REVIEW

**Comment by saghul** [comment]
I don't to run on `-latest` OS releases, because an upgrade may break them. I'd rather be explicit. WDYT @csett86 ?

**Comment by csett86** [comment]
I agree @saghul, I also like reproducible dependencies and build environments, so explicit versions instead of -latest

**Review by csett86 — CHANGES_REQUESTED** [review]
For all "runs-on", please use explicit versions instead of -latest to have reproducible dependencies and build environments.

**Review by RudraSen2 — COMMENTED** [review]
Requested Changes Fulfilled.

**Review by csett86 — APPROVED** [review]

**Comment by csett86** [comment]
Thanks, @RudraSen2

**Pull request merged**
