### PR TITLE
Merge changes upstream

### PR DESCRIPTION
**Pull request by awlx**
- Needs debranding
- Updates to Electron 8.2.0
- Updates to Nodejs 12

This build is proven to run on MacOS, Debian, Fedora and various variants of Windows.

If this is ok for you all, then I will work on the debranding. Otherwise feel free to close PR.

CC:
https://github.com/jitsi/jitsi-meet-electron/issues/224

### CODE REVIEW

**Comment by saghul** [comment]
Changes look ok to me, modulo branding.

**Comment by awlx** [comment]
@saghul Branding removed.

**Comment by awlx** [comment]
Merge conflict happens because of:
https://github.com/jitsi/jitsi-meet-electron/pull/214

Problem is the electron-builder used there triggers a Windows Defender Virus detection that's why I originally reverted that commit.

See:
https://github.com/electron-userland/electron-builder/issues/4793

**Comment by saghul** [comment]
Superseded by https://github.com/jitsi/jitsi-meet-electron/pull/227

**Pull request closed without merging**
