### PR TITLE
feat: force prejoin page instead of profile and av settings

### PR DESCRIPTION
**Pull request by csett86**
The settings and the prejoin page which is forced on many instances
including meet.jit.si did conflict, as you could set values in the
settings, then try to override them in den prejoin page only to notice
that it would not work. Clean this up by only having the prejoin page
where all settings can be done before joining the conference.

Closes: #687

### CODE REVIEW

**Comment by csett86** [comment]
@saghul please review

**Comment by csett86** [comment]
Need to fix the linting errors first, sorry for that

**Comment by csett86** [comment]
Now its looking good, also tested that onboarding still works, and overall a lot simpler. As @atlaskit/panel is now no longer used anywhere, I removed that dependency as well.

**Comment by JonnyTischbein** [comment]
I don't have that much experience how you review code in this project, but it looks good to me.

Thanks for your work :)

**Comment by saghul** [comment]
Ah bummer, I had the same PR ready but forgot my laptop lol so I couldn't push it. Oh well, great to see it. I'll give it a read.

Not sure you did, but if you didn't, can you move the server URL setting to the non-advanced settings section now?

**Review by saghul — APPROVED** [review]
LGTM! I see you removed the advanced expansion panel, I thought of keeping it but I think it will just simplify things, so let's go with your approach!

**Comment by JonnyTischbein** [comment]
Tested your branch on ubuntu 21.10 `5.13.0-22-generic #22-Ubuntu SMP Fri Nov 5 13:21:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

#687 is solved for me. I also tested successfully changing the username via the `settings` after joining the conference.

**Pull request merged**
