### PR TITLE
Add spanish i18n

### PR DESCRIPTION
**Pull request by Ark74**
Submitting Spanish internationalization.

### CODE REVIEW

**Comment by Ark74** [comment]
> You must update the https://github.com/jitsi/jitsi-meet-electron/blob/master/app/i18n/index.js file to add your lang file in it.

Thanks!, missed that.

**Comment by saghul** [comment]
Can you please fix the conflict?

**Comment by Ark74** [comment]
> Can you please fix the conflict?

done! thanks.

**Comment by Ark74** [comment]
@saghul could you merge?

**Pull request merged**
