### PR TITLE
ci: simplify thanks to prebuilds

### PR DESCRIPTION
**Pull request by csett86**
as @jitsi/robotjs and @jitsi/electron-sdk now have prebuilds, no need for build
tools here

### CODE REVIEW

**Comment by saghul** [comment]
Looks like Linux is unhappy

**Comment by csett86** [comment]
Indeed, prebuilds were not used during install, fixed it with

https://github.com/jitsi/robotjs/pull/7
https://github.com/jitsi/jitsi-meet-electron-sdk/pull/152

This PR is not urgent, obviously, I would wait for the next release of both deps until this then can be merged. Setting to draft until then.

**Comment by saghul** [comment]
Approved both, makes sense!

**Comment by csett86** [comment]
Now its ready as prebuilds are released (and used) here. As expected, build times on CI are also reduced a bit, thanks to the prebuilds.

**Review by saghul — APPROVED** [review]

**Pull request merged**
