### PR TITLE
deps: update electron-updater

### PR DESCRIPTION
**Pull request by saghul**
Fixes:
https://github.com/jitsi/jitsi-meet-electron/pull/674#issuecomment-983564898

### CODE REVIEW

**Comment by csett86** [comment]
4.4.6 is not a stable release of electron-updater, so if we want to update I suggest 4.6.1 as this is current latest on https://www.npmjs.com/package/electron-updater

**Comment by saghul** [comment]
oops

**Comment by saghul** [comment]
Updated.

**Comment by csett86** [comment]
Quick question on this: Did you test this with windows, mac and linux already? In addition, it currently conflicts...

**Comment by saghul** [comment]
No I didn't, we can actually revisit later. I thought we needed it for the last release but we don't...

**Pull request closed without merging**
