### PR TITLE
mac: Enable autoupdate by sign and notarize via github action

### PR DESCRIPTION
**Pull request by csett86**
Signed and notarized binaries are the precondition for autoupdates on
mac. Additionally Gatekeeper on 10.15+ is happy and allows to open the
app instead of blocking it.

The notarize step is added unconditionally, as it only emits a warning if
the notarization API key is not set, but it does not break the build.

This is an upstreaming of https://github.com/csett86/jitsi-meet-electron
where it worked since March 2020.

The required github secrets (signing key, cert and notarize API key) are
best described at https://github.com/samuelmeuli/action-electron-builder#code-signing

### CODE REVIEW

**Comment by csett86** [comment]
@saghul I created this pull request in the hope that at least the mac version could be signed & notarized so that auto-update works on mac and I could retire my signed & notarized fork for good, now that I can help maintain the project directly.

Certificates for mac at least are provided by Apple and don't need to be purchased separately, the Apple Developer Account used for the Jitsi iOS App should be sufficient for Mac signing & notarization as well.

**Comment by saghul** [comment]
But yeah, I'd love to have the macOS app signed.

**Comment by csett86** [comment]
Yes, "Developer ID Application" certificate is the correct one, and yes, unfortunately only the account holder can create that.

**Comment by csett86** [comment]
A good thing about the "Developer ID Application" certificates is: They are at least valid for 5 years...

**Comment by csett86** [comment]
@saghul I have updated the PR to remove a conflict. Any luck with finding someone who can provide the required Developer ID Application in your org? Still would love to see the mac app signed and notarized :)

**Comment by saghul** [comment]
Sorry I forgot about his after going on paternity leave. I’ll ask.

**Comment by saghul** [comment]
Thanks for keeping this alive!

Alas I have no updates, sorry.

**Comment by saghul** [comment]
I've got some good news!

```
  • packaging       platform=darwin arch=arm64 electron=13.5.2 appOutDir=dist/mac-universal--arm64
  • packaging       platform=darwin arch=universal electron=13.5.2 appOutDir=dist/mac-universal
  • signing         file=dist/mac-universal/Jitsi Meet.app identityName=Developer ID Application: 8x8, Inc. (FC967L3QRG) identityHash=96DF179CFD517DED9ABD95DA16D72C4872B4298D provisioningProfile=none
  • building        target=DMG arch=universal file=dist/jitsi-meet.dmg
  • building        target=macOS zip arch=universal file=dist/jitsi-meet.zip
  • building block map  blockMapFile=dist/jitsi-meet.dmg.blockmap
  • building block map  blockMapFile=dist/jitsi-meet.zip.blockmap
```

```
 spctl -a -t exec -v /Applications/Jitsi\ Meet.app
/Applications/Jitsi Meet.app: accepted
source=Notarized Developer ID
```

🚀 

I'll push some little updates here.

**Comment by saghul** [comment]
Updated the notarization process since it didn't work for me so I used the new `notarytool` method which did.

**Comment by saghul** [comment]
The secrets are already set in the repo.

**Review by saghul — APPROVED** [review]

**Comment by csett86** [comment]
What was the issue with electron-builder-notarize as its working fine for me (https://github.com/csett86/jitsi-meet-electron/blob/main/package.json#L24) and others (https://github.com/freifunkMUC/jitsi-meet-electron/blob/main/package.json#L24)

I prefer electron-builder-notarize as its not failing the build if notarize secrets are not set (just emitting a warning), thus we can keep it in package.json unconditionally...

**Comment by saghul** [comment]
I was getting this error:

```
  ⨯ Failed to upload app to Apple's notarization servers

*** Error: Notarization failed for '/var/folders/7l/_tnvl7wn6kb7fzs43pkyt2vw0000gn/T/electron-notarize-3I5ToN/Jitsi Meet.zip'.
*** Error: Unable to upload your app for notarization. --notarize-app is missing one or more required options: --asc-provider. (-1027)

usage: altool --upload-package <file> --type <platform> --asc-public-id <id> --apple-id <id>
                  --bundle-version <version> --bundle-short-version-string <string>
                  --bundle-id <id>
                  {-u <username> [-p <password>] | --apiKey <api_key> --apiIssuer <issuer_id>}
       altool --upload-hosted-content <file> --sku <sku> --type <platform> --product-id <id> --asc-provider <id>
                  {-u <username> [-p <password>] | --apiKey <api_key> --apiIssuer <issuer_id>}
       altool --validate-app -f <file> -t <platform>
                  {-u <username> [-p <password>] | --apiKey <api_key> --apiIssuer <issuer_id>}
       altool --upload-app -f <file> -t <platform>
                  {-u <username> [-p <password>] | --apiKey <api_key> --apiIssuer <issuer_id>}
       altool --notarize-app -f <file> --primary-bundle-id <bundle_id>
                  {-u <username> [-p <password>] | --apiKey <api_key> --apiIssuer <issuer_id>}
                  [--asc-provider <name> | --team-id <id> | --asc-public-id <id>]
       altool --notarization-info <uuid>
                  {-u <username> [-p <password>] | --apiKey <api_key> --apiIssuer <issuer_id>}
       altool --notarization-history <page>
                  {-u <username> [-p <password>] | --apiKey <api_key> --apiIssuer <issuer_id>}
                  [--asc-provider <name> | --team-id <id> | --asc-public-id <id>]
       altool --list-apps
                  {-u <username> [-p <password>] | --apiKey <api_key> --apiIssuer <issuer_id>}
       altool --list-providers
                  {-u <username> [-p <password>] | --apiKey <api_key> --apiIssuer <issuer_id>}
       altool --store-password-in-keychain-item <keychain_item_name> -u <username> -p <password>
                  [--keychain <filename> | --sync]
  failedTask=build stackTrace=Error: Failed to upload app to Apple's notarization servers
```

I'll fix the script so it doesn't fail.

**Review by saghul — APPROVED** [review]

**Comment by olivluca** [comment]
I'm not really interested in generating mac binaries, but without secrets the build fails
https://github.com/olivluca/jitsi-meet-electron/runs/4114626313?check_suite_focus=true

**Pull request merged**
