### PR TITLE
Revert "deps: Update electron-builder to 22.11.1"

### PR DESCRIPTION
**Pull request by csett86**
Reverts jitsi/jitsi-meet-electron#574

The electron-builder update breaks artifact publishing to Github releases, thus reverting.

### CODE REVIEW

**Comment by csett86** [comment]
Duplicate of #577

**Comment by saghul** [comment]
Hey @csett86 you seem to care about this package quite a bit. Would you be interested in getting the commit bit to help out with maintenance?

**Comment by csett86** [comment]
Hi @saghul, yes, thank you for the offer, that sounds great, as I anyway maintain https://github.com/HoppFoundation/jitsi-meet-electron and support from time to time with https://github.com/freifunkMUC/jitsi-meet-electron

**Comment by saghul** [comment]
Excellent, I'll add you as a maintainer.

**Comment by saghul** [comment]
Done.

**Comment by csett86** [comment]
Thank you, invitation already accepted

**Pull request closed without merging**
