### PR TITLE
fix: add sandbox permission to iframe

### PR DESCRIPTION
**Pull request by andreicon**

### CODE REVIEW

**Comment by saghul** [comment]
Change LGTM but I don't think it's enough for the download to happen. Have you tested this?

**Comment by andreicon** [comment]
hi, saghul,

yes, i've tested this and the issue was fixed by adding that policy.

**Comment by saghul** [comment]
How and where is the file actually downloaded?

**Comment by andreicon** [comment]
The system's default "Save File" dialog is triggered by the web view. The user can then choose a location and specify a file name. I believe excalidraw specifies a mime type for the file, so the dialog already hints the file extension.

**Comment by saghul** [comment]
That is pretty cool!

**Review by saghul — APPROVED** [review]

**Pull request merged**
