### PR TITLE
Fix running AppImage on Debian 10+ (#231 )

### PR DESCRIPTION
**Pull request by csett86**
Move the real binary to jitsi-meet.bin and create a wrapper script (thanks to https://github.com/electron-userland/electron-builder/issues/5371#issuecomment-791771150) that contains the --no-sandbox and is also used in the AppImage.

With this we can remove the documented workaround and the AppImage runs fine on Debian 10+ as well.

The patch for app-builder-lib can also be dropped, as the desktop file now calls the wrapper script which then adds the --no-sandbox as a param when executing the actual binary.

### CODE REVIEW

**Comment by csett86** [comment]
@saghul This pull request is now ready for review. I have squashed the commits in the end as it was a bit of back and forth that history is not really relevant to be kept for later.

Looking forward to get this reviewed as this finally removes the manual workaround of launching with --no-sandbox on Debian 10+.

**Review by saghul — APPROVED** [review]
LGTM, thanks for fixing this! I'll give it a quick test.

**Comment by csett86** [comment]
@saghul This breaks the jitsi-meet:// protocol handling, I will rework it. Please dont merge yet!

**Comment by csett86** [comment]
@saghul jitsi-meet:// protocol handling now also continues to work (as it should), the order of args in the wrapper script was simply wrong...

**Review by saghul — APPROVED** [review]

**Pull request merged**
