### PR TITLE
deps: Update electron-builder to 22.11.1

### PR DESCRIPTION
**Pull request by csett86**
Signed-off-by: Christoph Settgast <csett86@web.de>

### CODE REVIEW

**Comment by saghul** [comment]
Any interesting features we're getting out of this?

**Comment by csett86** [comment]
Mostly small bugfixes like "DMG assembly on Apple Silicon", "extend http file limit" and the possibility to specify the package name for linux packages (like deb), but nothing really important.

So I consider it a small update just to keep up to date what everyone else is using.

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Hum, I just tried to make a new release and the artifacts are not being published to the draft release. Have you observed this? This dependency is the only relevant one I think.

**Comment by csett86** [comment]
@saghul yes, I can reproduce the issue as well. That seems to be a regression from that electron-builder release. Please excuse the hassle, I suggest to revert this pull request for now.

**Comment by saghul** [comment]
👍

**Pull request merged**
